// Generated by CoffeeScript 1.9.1
var Car;

Car = (function() {
  function Car(year, make, model, owner) {
    this.year = year;
    this.make = make;
    this.model = model;
    this.owner = owner;
    this.odom = 0;
    this.mpg = 15;
    this.tank = 22;
    this.FULLTANK = 22;
  }

  Car.prototype.getYear = function() {
    return this.year;
  };

  Car.prototype.getMake = function() {
    return this.make;
  };

  Car.prototype.getModel = function() {
    return this.model;
  };

  Car.prototype.getOwner = function() {
    return this.owner;
  };

  Car.prototype.setOwner = function(newOwner) {
    return this.owner = newOwner;
  };

  Car.prototype.getOdom = function() {
    return this.odom;
  };

  Car.prototype.setOdom = function(newOdom) {
    return this.odom = newOdom;
  };

  Car.prototype.getMPG = function() {
    return this.mpg;
  };

  Car.prototype.setMPG = function(newMPG) {
    return this.mpg = newMPG;
  };

  Car.prototype.getFuel = function() {
    return (this.tank / this.FULLTANK) * 100;
  };

  Car.prototype.setFullTank = function(newTank) {
    this.FULLTANK = newTank;
    return this.tank = newTank;
  };

  Car.prototype.drive = function(miles) {
    this.tank -= Math.floor(miles / this.mpg);
    return this.odom += miles;
  };

  Car.prototype.fillUp = function() {
    var total;
    total = this.FULLTANK - this.tank;
    this.tank = this.FULLTANK;
    return total;
  };

  return Car;

})();

module.exports = Car;
